
export const cantantes = [
    { nombre: 'ABBA', genero: 'Pop', nacionalidad: 'Sueco', edad: 70, discos: 9, canciones: 100 },
    { nombre: 'Adele', genero: 'Soul', nacionalidad: 'Británica', edad: 35, discos: 4, canciones: 60 },
    { nombre: 'Alejandro Fernández', genero: 'Ranchera', nacionalidad: 'Mexicano', edad: 50, discos: 20, canciones: 300 },
    { nombre: 'Alejandro Sanz', genero: 'Pop', nacionalidad: 'Español', edad: 52, discos: 12, canciones: 150 },
    { nombre: 'Álvaro Soler', genero: 'Pop', nacionalidad: 'Español', edad: 33, discos: 3, canciones: 60 },
    { nombre: 'Ana Gabriel', genero: 'Balada', nacionalidad: 'Mexicana', edad: 65, discos: 30, canciones: 500 },
    { nombre: 'Andrea Bocelli', genero: 'Ópera', nacionalidad: 'Italiano', edad: 65, discos: 17, canciones: 200 },
    { nombre: 'Beyoncé', genero: 'R&B', nacionalidad: 'Estadounidense', edad: 42, discos: 7, canciones: 100 },
    { nombre: 'Bob Marley', genero: 'Reggae', nacionalidad: 'Jamaicano', edad: 36, discos: 13, canciones: 150 },
    { nombre: 'Bruno Mars', genero: 'Pop', nacionalidad: 'Estadounidense', edad: 38, discos: 3, canciones: 80 },
    { nombre: 'Camilo Sesto', genero: 'Balada', nacionalidad: 'Español', edad: 72, discos: 40, canciones: 700 },
    { nombre: 'Celia Cruz', genero: 'Salsa', nacionalidad: 'Cubana', edad: 77, discos: 20, canciones: 300 },
    { nombre: 'David Bowie', genero: 'Rock', nacionalidad: 'Británico', edad: 69, discos: 25, canciones: 300 },
    { nombre: 'Dima Bilan', genero: 'Pop', nacionalidad: 'Ruso', edad: 42, discos: 9, canciones: 100 },
    { nombre: 'Ed Sheeran', genero: 'Pop', nacionalidad: 'Británico', edad: 33, discos: 6, canciones: 120 },
    { nombre: 'Elvis Presley', genero: 'Rock and Roll', nacionalidad: 'Estadounidense', edad: 42, discos: 24, canciones: 300 },
    { nombre: 'Emmanuel', genero: 'Balada', nacionalidad: 'Mexicano', edad: 66, discos: 30, canciones: 500 },
    { nombre: 'Enya', genero: 'New Age', nacionalidad: 'Irlandesa', edad: 62, discos: 9, canciones: 80 },
    { nombre: 'Eros Ramazzotti', genero: 'Pop', nacionalidad: 'Italiano', edad: 60, discos: 14, canciones: 180 },
    { nombre: 'Freddie Mercury', genero: 'Rock', nacionalidad: 'Británico', edad: 45, discos: 15, canciones: 180 },
    { nombre: 'Gloria Estefan', genero: 'Pop', nacionalidad: 'Cubana', edad: 64, discos: 15, canciones: 200 },
    { nombre: 'Helene Fischer', genero: 'Schlager', nacionalidad: 'Alemana', edad: 39, discos: 8, canciones: 90 },
    { nombre: 'Joaquín Sabina', genero: 'Cantautor', nacionalidad: 'Español', edad: 72, discos: 17, canciones: 200 },
    { nombre: 'José José', genero: 'Balada', nacionalidad: 'Mexicano', edad: 71, discos: 30, canciones: 400 },
    { nombre: 'Juan Gabriel', genero: 'Balada', nacionalidad: 'Mexicano', edad: 71, discos: 50, canciones: 1000 },
    { nombre: 'Juanes', genero: 'Rock', nacionalidad: 'Colombiano', edad: 49, discos: 7, canciones: 100 },
    { nombre: 'Julio Iglesias', genero: 'Balada', nacionalidad: 'Español', edad: 78, discos: 80, canciones: 1500 },
    { nombre: 'Luis Aguile', genero: 'Balada', nacionalidad: 'Argentino', edad: 73, discos: 20, canciones: 300 },
    { nombre: 'Luis Fonsi', genero: 'Pop', nacionalidad: 'Puertorriqueño', edad: 43, discos: 9, canciones: 100 },
    { nombre: 'Luis Miguel', genero: 'Balada', nacionalidad: 'Mexicano', edad: 51, discos: 20, canciones: 200 },
    { nombre: 'Luis Miguel', genero: 'Bolero', nacionalidad: 'Mexicano', edad: 54, discos: 20, canciones: 200 },
    { nombre: 'Marco Antonio Solís', genero: 'Balada', nacionalidad: 'Mexicano', edad: 61, discos: 30, canciones: 500 },
    { nombre: 'Michael Jackson', genero: 'Pop', nacionalidad: 'Estadounidense', edad: 50, discos: 10, canciones: 150 },
    { nombre: 'Mireille Mathieu', genero: 'Chanson', nacionalidad: 'Francesa', edad: 77, discos: 40, canciones: 400 },
    { nombre: 'Mylène Farmer', genero: 'Pop', nacionalidad: 'Francesa', edad: 62, discos: 11, canciones: 150 },
    { nombre: 'Paul McCartney', genero: 'Rock', nacionalidad: 'Británico', edad: 81, discos: 30, canciones: 500 },
    { nombre: 'Raphael', genero: 'Balada', nacionalidad: 'Español', edad: 80, discos: 40, canciones: 400 },
    { nombre: 'Ricardo Arjona', genero: 'Balada', nacionalidad: 'Guatemalteco', edad: 57, discos: 16, canciones: 200 },
    { nombre: 'Ricardo Montaner', genero: 'Balada', nacionalidad: 'Venezolano', edad: 63, discos: 25, canciones: 400 },
    { nombre: 'Ricky Martin', genero: 'Pop', nacionalidad: 'Puertorriqueño', edad: 50, discos: 10, canciones: 150 },
    { nombre: 'Roberto Carlos', genero: 'Balada', nacionalidad: 'Brasileño', edad: 80, discos: 40, canciones: 600 },
    { nombre: 'Rocío Dúrcal', genero: 'Ranchera', nacionalidad: 'Española', edad: 61, discos: 30, canciones: 400 },
    { nombre: 'Roxette', genero: 'Pop Rock', nacionalidad: 'Sueco', edad: 63, discos: 10, canciones: 100 },
    { nombre: 'Ruslana', genero: 'Pop', nacionalidad: 'Ucraniana', edad: 50, discos: 7, canciones: 80 },
    { nombre: 'Salvatore Adamo', genero: 'Chanson', nacionalidad: 'Belga', edad: 80, discos: 20, canciones: 300 },
    { nombre: 'Sarah Connor', genero: 'Pop', nacionalidad: 'Alemana', edad: 43, discos: 12, canciones: 140 },
    { nombre: 'Shakira', genero: 'Pop', nacionalidad: 'Colombiana', edad: 47, discos: 11, canciones: 150 },
    { nombre: 'Sting', genero: 'Rock', nacionalidad: 'Británico', edad: 72, discos: 15, canciones: 250 },
    { nombre: 'Tarkan', genero: 'Pop', nacionalidad: 'Turco', edad: 51, discos: 10, canciones: 120 },
    { nombre: 'Vicente Fernández', genero: 'Ranchera', nacionalidad: 'Mexicano', edad: 81, discos: 50, canciones: 600 },
    { nombre: 'Vitas', genero: 'Pop', nacionalidad: 'Ruso', edad: 45, discos: 10, canciones: 130 },
    { nombre: 'Whitney Houston', genero: 'R&B', nacionalidad: 'Estadounidense', edad: 48, discos: 7, canciones: 100 },
    { nombre: 'Zaz', genero: 'Chanson', nacionalidad: 'Francesa', edad: 44, discos: 5, canciones: 70 },
    
];